### ISSUE TITLE
Not compatible with Python 3 & Python 2.6 

### ISSUE THREAD

**Issue by averagehat** [VDBWRAIR/samtools#1]
The tests imported from ngs_mapper (and maybe some of the other code) use python-2 `print` and python-2.7 dictionary-comprehensions, among other probable compatibility problems. 

I found this useful: http://python-future.org/compatible_idioms.html

**Comment by necrolyte2** [comment]
All code you get from ngs_mapper is only tested under 2.7

Yay!

**Comment by necrolyte2** [comment]
In all new projects I have travis and tox check 2.6, 2.7 and 3.4
